# Programming language
language: java

before_install:
  # Install the tool to switch between JDK versions
  - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh

script: mvn verify -DskipTests=true -Dmaven.javadoc.skip=true -B -V

### Maven basic build ###
jobs:
  include:
    - stage: deploy
      jdk: openjdk8 # Use the minimal supported version (this assures that no version-specific bytecode gets generated)
      if: repo = CatCoderr/ProtocolSidebar AND branch IN (master, dev) AND type != pull_request
      script: source ./attempt-travis-deploy.sh

# Cached directories
cache:
  directories:
    - ~/.m2/repository # Maven repository