name: Maven Build & Deploy

on: [ push ]

env:
  ENCRYPTED_CODESIGNING_IV: ${{ secrets.ENCRYPTED_CODESIGNING_IV }}
  ENCRYPTED_CODESIGNING_KEY: ${{ secrets.ENCRYPTED_CODESIGNING_KEY }}
  GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
  GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
  SONATYPE_OSSRH_DEPLOYER: ${{ secrets.SONATYPE_OSSRH_DEPLOYER }}
  SONATYPE_OSSRH_TOKEN: ${{ secrets.SONATYPE_OSSRH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build & Deploy
        run: ./attempt-deploy.sh
        shell: bash
